# NOTE:
# README: https://hub.docker.com/_/mysql
# CREDENTIALS: root/example
# CREDENTIALS: myuser/mypassword
# CONNECT to adminer: http://localhost:8080/?server=db&username=root
# USE COMMAND: docker compose -f db_mysql.yaml up -d
# INIT SQL FILE: must be in the same directory as yaml file

version: '3.1'

services:

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  apiserver:
    build: ./api/
    restart: always
    ports:
      - 8081:8081
