version: '3.1'

services:

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/dump.sql
        #ports:
        #- 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  apiserver:
    build: ./api/
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - database
      - adminer

  crawler:
    build: ./crawler/
    restart: always
    depends_on:
      - database
      - adminer
